### ISSUE TITLE
Enabling and disabling datapacks in-game

### ISSUE THREAD

**Issue by MaliMiau** [MacaylaMarvelous81/DatapackInstaller#3]
Would be awesome if you could open the datapack selection screen while in-game and enable/disable them after creating the world.

**Comment by MacaylaMarvelous81** [comment]
Do you mean accessing it while loaded into the world, or just be able to access it in the game after the world was created?

**Comment by MaliMiau** [comment]
Either way does the job I guess

**Comment by MaliMiau** [comment]
omg i dont know how to use this im sorry

**Comment by MacaylaMarvelous81** [comment]
Since 1131a60 there is now a button in the Game Menu (aka Pause Menu) that will allow you to select the data packs. It will reload data packs once you close the screen. It doesn't work with those that require feature flags (like the built-in bundle data pack) since they require feature flags (similarly, they can't be enabled or disabled with the vanilla datapack command)
